### ISSUE TITLE
LaTeX not functional

### ISSUE THREAD

**Issue by DannyLeWasTaken** [1bl4z3r/hermit-V2#15]
Hello! While going through the demo website I've noticed that the LaTeX is no longer working and isn't showing up anymore. It can be seen here: https://1bl4z3r.github.io/hermit-V2/posts/typography/. Here is what I'm seeing on my end: https://i.imgur.com/xKxJfZa.png
I am using LibreWolf on Windows 10.

**Comment by 1bl4z3r** [comment]
Hi,
Its me again.

I was going though many Hugo blogs and discourse in the morning. I found that there are two implementations for LaTeX for web use :
Source : [katex vs mathjax - Trust In Geeks](https://www.trustingeeks.com/coding/katex-vs-mathjax/)

- MathJax 
    - It is slow
    - It has close to complete LaTeX support
    - MathJax stands out for its comprehensive support for LaTeX, making it the go-to choice for applications that require full compatibility with LaTeX syntax and advanced mathematical formatting.

- KaTeX 
    - It is blazing fast
    - It has incomplete LaTeX support
    - KaTeX is known for its impressive speed and efficiency in rendering mathematical expressions, making it a suitable option for applications that prioritize performance.

I'm thinking about implementing MathJax as it is comprehensive. Hugo is fast, so I do not believe that MathJax's slowness is going to affect much.

That's the update for now

**Comment by 1bl4z3r** [comment]
I was building up a concept and looking for a good way to implement. This is what I was able to cook up. As you can see TeX is rendered, but many fonts are missing.
I did not know there is a font library

![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/a5e40c51-323a-4dfc-adb6-e79a78591767)

**Comment by 1bl4z3r** [comment]
Yayy!!!

I switched from chtml render to svg render. Console is clear. I love it

![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/9e42cd8b-8e5a-4a8c-9a33-78ddf249c8ed)

**Comment by 1bl4z3r** [comment]
Hello @DannyLeWasTaken,

I have pushed new changes with [LaTeX implementation](https://github.com/1bl4z3r/hermit-V2/tree/v0.0.5).
Kindly check if you are able to use LaTeX.

I am keeping this Issue open for a week, in-case there is any issues.

**Comment by 1bl4z3r** [comment]
Closing this Issue, as no response was provided.
Kindly re-open if issue persists
