### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by minima1cha0s** [1bl4z3r/hermit-V2#16]
Update README so that new users can install your repo as a git submodule instead of still using the original repo.

**Comment by 1bl4z3r** [comment]
Hi @minima1cha0s,

I have [pushed new changes](https://github.com/1bl4z3r/hermit-V2/tree/v0.0.5) and updated installation guide.

It was an oversight from my part. Thanks for letting me know.
I am closing this issue.

I hope you would enjoy Hermit - V2
