### ISSUE TITLE
double font-size

### ISSUE THREAD

**Issue by lookfirst** [1bl4z3r/hermit-V2#21]
Hi there! =) Which one should it be?

![2023-09-26 at 03 39 20 png](https://github.com/1bl4z3r/hermit-V2/assets/85355/7887c528-c180-41d6-b060-d4b3f12b7675)

**Comment by 1bl4z3r** [comment]
Hi @lookfirst,
Ideally it should be `0.875rem`. In CSS, `14px` is gonna be ignored anyways as it comes first.

However, I will admit that I have no idea about screen readers or how it renders various components.

**Comment by lookfirst** [comment]
IDEA flags this as a double attribute warning. Should probably delete the 14px then. Thanks!

**Comment by 1bl4z3r** [comment]
Yep, that is the most logical thing to do.
I will push a release this weekend. Kindly bear with me :-)

**Comment by 1bl4z3r** [comment]
Removed that line. Should be now fine.
:-)
