### ISSUE TITLE
Request: example site's GitHub button pointing to this repo

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#23]
The demo site's GitHub icon here: https://1bl4z3r.github.io/hermit-V2/

Instead of just pointing to https://github.com/, can we have it take us to either:
- This repo
- Example site's source code

Thank you in advance!

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,
That is very logical thing to do. I am now kicking myself for not thinking about this earlier.

Give me 12 hours, I will update this.

**Comment by 1bl4z3r** [comment]
Kicking complete.
Updated GitHub button to redirect to the source.

Welcome NEO
