### ISSUE TITLE
Request: code block limiting width with scroll bar

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#24]
As of version 1.0.0, looking at the example site's MathJax post: https://1bl4z3r.github.io/hermit-V2/posts/mathjax-support/

The left/right scrolling is huge due to the first code block in the configuration section.

Any thoughts on having the scrolling limited to within the code block (and not the entire page)?

As an example, check out the code blocks here work (left/right scrolling is scoped to the code block): https://blowfish.page/docs/shortcodes/#alert

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

Thank you again.
Let me check this. I will update as soon as possible.

Additionally, if you are able, could you give me a screenshot of the issue. It will help me a lot.

**Comment by jamesbraza** [comment]
Yeah sure! I have pasted a screenshot below:

![screenshot of what I meant](https://github.com/1bl4z3r/hermit-V2/assets/8990777/32eb8c76-637b-43ec-a22f-4cdd1970946f)

Basically the first code block goes way off the screen, and you can see a left-to-right scrollbar appears on the bottom.  It would be cool if the scroll bar is inside the code block, not for the entire screen.  Take a look at that Blowfish theme's link in the first post for a reference.

Let me know if the request still doesn't quite make sense

**Comment by 1bl4z3r** [comment]
Got it.

Either it will be a horizontal scrollbar or the code will be auto word-wrapped.

No promises on what I could implement though.

**Comment by 1bl4z3r** [comment]
Added scroll bar on code block, as this was easier.
![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/2a54c473-f0fd-4ebd-a0d2-628d6c55a002)

**Comment by jamesbraza** [comment]
Thank you @1bl4z3r ! Looks great, and can now scroll down that page nicely
