### ISSUE TITLE
Very happy to see this!!

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#25]
I am a fan of Hugo's Hermit theme, and use it for my blog [onetwofoureight.com](https://onetwofoureight.com/).

I was going to change theme to one with a page sharing feature, however, I came across this today. And coincidentally, the v1 release was this morning, haha wow!

Very excited to transition to this, cheers!

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

As a matter of fact, I am using my theme for my blog as well 😅.

As always, thank you for transitioning.
