### ISSUE TITLE
Request: linking example site's source in `README`

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#26]
I am not finding it obvious where the source content underlying the example site is: https://1bl4z3r.github.io/hermit-V2/

Can a link be posted in the README for the example site?

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

The example site is in [staging branch](https://github.com/1bl4z3r/hermit-V2/tree/staging).

I am going to update README for the same. Thanks for noticing.

**Comment by 1bl4z3r** [comment]
README is now updated to reflect the Example sites' source.
https://github.com/1bl4z3r/hermit-V2#demo

Thank you again
