### ISSUE TITLE
Request: configuration reference table

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#27]
Check out https://blowfish.page/docs/configuration/, it has a sequence of tables that document `hugo.toml` or frontmatter parameters:

- Name
- Default
- Description

It would be nice if Hermit-V2 had a similar post documenting configuration parameters with defaults/descriptions

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

This is a good suggestion TBH.
I had thought about doing this a long tome back (honestly it had been only 4 months), but didn't as in `hugo.toml` everything is commented there and unlike Blowfish's, there isn't much config flags in the first place.

Let me know if you want a dedicated page for the config. I will see whatever I can ccokup.

**Comment by jamesbraza** [comment]
Thanks for consideration! Yeah with the current config, it shows many options, but it doesn't show:
- If it's a comprehensive list of all options (e.g. if some aren't present)
- The default values of most options

For example:
- [`themeColor`](https://github.com/1bl4z3r/hermit-V2/blob/v1.0.2/hugo.toml#L74): is the default "#494f5c"? Or is that just the configured value
- [`hasCJKLanguage`](https://github.com/1bl4z3r/hermit-V2/blob/v1.0.2/hugo.toml#L39): it's commented out, but it would appear its default is `true`. It's be good to document the default on parameters like this

So feel free to go with config comments or config table, just have it such that default values are explicit and shows all possible configuration parameters.

**Comment by 1bl4z3r** [comment]
Got it.
You got a work cut out for me.

Keeping issue open until then.

**Comment by 1bl4z3r** [comment]
Hi, updated a page [Explaining Configs](https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/).

Closing this issue. Re-open if you want further clarifications.

**Comment by jamesbraza** [comment]
Thank you for getting it started!  Appreciated, will be a shell to grow into over time
