### ISSUE TITLE
Request: `index.html` using `footer.html` partial

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#29]
In https://github.com/1bl4z3r/hermit-V2/issues/28 I was able to override my `footer.html` partial.

However, I discovered `index.html` doesn't use the `footer.html` partial. Can we move `index.html` to either:

- Move `home-footer.html` to a partial that can be overridden
- Have `index.html` use the `footer.html` partial

Thank you in advance for your consideration

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

That could be done, yes.
Give me a day for this as well.

**Comment by 1bl4z3r** [comment]
Added an extra partial `single-footer` for be able to be modified.
We cannot use same footer partial because:

1. it is long
2. it will require some major stylesheet changes

Closing this issue

**Comment by jamesbraza** [comment]
Thank you!! 🚀
