### ISSUE TITLE
Possibly extra dot in `single-footer.html`

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#31]
Currently from https://1bl4z3r.github.io/hermit-V2/:

![screenshot of current Hermit-V2 demo's homepage footer](https://github.com/1bl4z3r/hermit-V2/assets/8990777/e097b702-d71b-49bb-b138-51671f7f63c7)

It seems to me there is either:

- A missing middle dot between the name and CC BY-NC
- An extra "middle dot between CC BY-NC and the RSS logo

Do you agree? Imo it's visually imbalanced at the moment

**Comment by jamesbraza** [comment]
Here is how my hermit (v1) site does it: https://onetwofoureight.com/

![screenshot of bottom bar in v1](https://github.com/1bl4z3r/hermit-V2/assets/8990777/ef3b5379-e5c9-4743-ba1c-33b671ddcb0b)

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

I really applaud to your keen observation. It had eluded me for quite sometime.
I am pushing a fix

**Comment by 1bl4z3r** [comment]
Added extra dot.
Closing this issue
