### ISSUE TITLE
Recent code changes to `main` branch?

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#32]
The recent changes have been awesome, I am looking to use them now.

Either:

- I can set my `git submodule` to use the `staging` branch
- hermit-V2's `main` branch can be updated

Do you mind updating the `main` branch?  I think having the example site diverge from the `main` branch can be confusing to new users

**Comment by jamesbraza** [comment]
Actually, changing my submodule to use `staging` branch doesn't work because it then pulls in all the example site's posts too.  Any chance you wouldn't mind updating the `main` branch with recent fixes?

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

All files (sans Content and Static directory) is copied to main.
Every push to staging gets propagated to main (minus static and content)

**Comment by 1bl4z3r** [comment]
You really shouldn't pull staging branch as it contains blog contents which will result in useless spacehog. You should instead pull from main or submodule into themes folder.

**Comment by jamesbraza** [comment]
Oh actually, I understand how things work now (I had some misgivings):

1. `staging` has a GitHub Action to commit changes to `main`: https://github.com/1bl4z3r/hermit-V2/blob/0b24b5fcbd2788f1d1f4e98a3c9fc3990e29decd/.github/workflows/staging-workflow.yml#L14
2. These commits show up as "Theme Files Update" as made by a GitHub bot

I use https://github.com/refined-github/refined-github browser plugin, which has "dim bots" to grey out bot commits (here is a GIF from https://github.com/refined-github/refined-github#conversations):

![dim bot example](https://user-images.githubusercontent.com/1402241/220607557-f8ea0863-f05b-48c8-a447-1fec42af0afd.gif)

Here's a screenshot of how the hermit-V2 commit history looks for me:

![screenshot of commit history](https://github.com/1bl4z3r/hermit-V2/assets/8990777/ae9b53e4-1e60-4179-9289-55f214c39055)

I apologize for this @1bl4z3r, but I didn't realize these bot commits actually had meaningful content 😓 . I thought it was like Dependabot meaningless commits.

Closing this out!

**Comment by 1bl4z3r** [comment]
This project isn't such high profile to have dependabot 😅, also I am lazy AF.

Still, have a nice day I guess
