### ISSUE TITLE
Placing post metadata on bottom of post

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#33]
The original hermit theme placed post metadata like tags, Git commit, and word count on the bottom of the post.

It seems hermit-V2 is placing that metadata on the top of a post.  Is there any way to control if metadata goes at the top or bottom or the page?

**Comment by jamesbraza** [comment]
My view is to focus on the core content, and less on word count, Git commit, Hugo tag, etc. So I liked putting post metadata on the bottom.

If you don't want to support this expanded post configuration, I can just override the `posts/single.html` layout myself.  Let me know if you feel like implementing this 🤓 👍

**Comment by 1bl4z3r** [comment]
Sure, that won't be a problem. I will copy paste from OG single.html with an if statement.

It will be 'enableLegacyLayout:true' in hugo.toml

**Comment by jamesbraza** [comment]
I wonder if you could make the post metadata a partial, and then use that within the `if` statement for DRY code

**Comment by 1bl4z3r** [comment]
That's exactly my 2nd thought.

Suffering from acid reflux today, will push tomorrow.

**Comment by 1bl4z3r** [comment]
Pushed a change.
Make `legacyLayout` to true in hugo.toml

You can extend partial from `/theme/layouts/partials/posts_single_info.html` to edit page info according to your needs.

Closing this issue. Re-open if required.

**Comment by jamesbraza** [comment]
Wonderful! Will give it a try, I think this is the last change I will need to complete my migration to this theme. Thanks again!
