### ISSUE TITLE
Request: repositioning `post-end` when `legacyLayout = true`

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#34]
When `legacyLayout = true`, I find the `post-end` bar seems to be in the wrong place. See the below screenshot:

<img width="400" alt="screenshot of post-end" src="https://github.com/1bl4z3r/hermit-V2/assets/8990777/d3ecb057-a1fd-45fa-90a6-ce7f941fb55c">

I think a few options for when `legacyLayout = true`:

- Disable `post-end` in favor of `art-end`
- Disable `art-end` and move `post-end` above the metadata (what hermit v1 has)

What do you think?  Thanks in advance

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza
Yep, my bad. I zoned out while checking the layout and failed to differentiate. Pushing a change within an hour.

**Comment by 1bl4z3r** [comment]
I think it is better (for legacy compatibility) to have art-end disabled.

**Comment by 1bl4z3r** [comment]
This is how layout will look.
![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/f6f94a35-1370-468b-bda9-272e86ec8e2a)

Closing this issue. Re-open if required
