### ISSUE TITLE
Getting warning about author key being deprecated

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#39]
With Hugo 0.120.3, I am getting a warning:

```
> hugo server -D
...
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended darwin/arm64 BuildDate=2023-11-01T17:57:00Z VendorInfo=gohugoio

WARN  The author key in site configuration is deprecated. Use params.author.name instead.
```

Any chance we can update https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/ to match this?

Thanks in advance

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,
I saw this yesterday and concluded to keep that for future me. Now, I'm that future me.
I will push a change shortly

**Comment by 1bl4z3r** [comment]
Changes pushed.
Warning should be resolved.

Closing Issue

**Comment by jamesbraza** [comment]
Haha thanks for knocking this out! Appreciate your fast work 👍 .

Fyi I am hitting a slight follow up issue, which I describe in https://github.com/1bl4z3r/hermit-V2/issues/42
