### ISSUE TITLE
Request: `shareSocial` option to copy link to clipboard

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#41]
Here is what my current share menu looks like (as of https://github.com/1bl4z3r/hermit-V2/commit/3eabdaf2b46a01d2abe0e137919c2f9c825a8f43), and it looks great. 🥳 

<img width="50" alt="screenshot of share menu" src="https://github.com/1bl4z3r/hermit-V2/assets/8990777/6e9dea07-2fbe-4499-a143-adf2407c023c">

For many share features on other website, a sharing option is supported that copies the page's hyperlink to the clipboard. On Google Chrome's mobile app, this sharing option is called "Copy link".

My request here: add a share option for just copying the page's link to the clipboard

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,
I was unable to understand your question completely. Could you please describe a workflow.

As I can see, long press ilon the share links (on chrome mobile) opens context menu to copy link.

**Comment by jamesbraza** [comment]
Yeah sorry for being unclear, let me elaborate 👌

> long pressing icon of the share links (on chrome mobile) opens context menu to copy link.

My thinking here is, this is a possible route on mobile, but not necessarily on computers. Also, fwiw one has to know to long-press on the title.

I find an explicit "copy link" icon as part of the share modal, something like this (in blue box):

<img src="https://github.com/1bl4z3r/hermit-V2/assets/8990777/cbe36554-0819-41ba-8870-e8a46f335125" width="300" />

Though it doesn't need to actually have the text "copy link". Another possible route I found here from JIRA:

<img width="116" alt="screenshot of JIRA share" src="https://github.com/1bl4z3r/hermit-V2/assets/8990777/8c1c3b2b-52a7-4d7d-a71d-eedc2d3b2259">

And another, this one is from Google Drive:

<img width="500" alt="screenshot of Google Drive share" src="https://github.com/1bl4z3r/hermit-V2/assets/8990777/8a544983-d567-4715-8adc-d32998435244">

Does that clarify what I am looking for?  One of these copy link icons in the share socials modal

**Comment by 1bl4z3r** [comment]
Yeah, that can be done.
I will try to hook into browsers' Share API (which will bring up share page like your first image) for mobile and Clipboard API (to simply copy the link) for desktops.

There will be checks nonetheless if browsers supports the API.

Let me know if you are on board with this.

**Comment by jamesbraza** [comment]
Yeah I like what you're thinking with outsourcing to browser. For me, I am primarily a desktop user.

Thanks for being open to this! 👍

**Comment by 1bl4z3r** [comment]
Sure, its a few lines of JS. Changes will be there shortly

**Comment by 1bl4z3r** [comment]
Added Share link. If you want to change order, you may extend the partial.
![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/da601bc0-23b4-4b2b-830e-fb2a31c740aa)


It first checks if browser supports Webshare API, if yes, it will ask Browser/OS to open Share Link
Else it invokes Clipboard API to copy the URL (Clipboard cannot copy much BTW).
If everything fails, you will get Console output.

Closing this issue

**Comment by jamesbraza** [comment]
Gave it a try just now, and it worked!! Yaayy!

Nice job @1bl4z3r 👍
