### ISSUE TITLE
Unintended side effect of `[params.author]`

### ISSUE THREAD

**Issue by jamesbraza** [1bl4z3r/hermit-V2#42]
The fix in https://github.com/1bl4z3r/hermit-V2/commit/556699fcd783d9803ada8b7cd7c908a7eb7e362c has a side effect, which is my site starts using the hermit-V2's `about` option from the repo's `hugo.toml`: https://github.com/1bl4z3r/hermit-V2/blob/556699fcd783d9803ada8b7cd7c908a7eb7e362c/hugo.toml#L41

It leads to this error:

```
> hugo server -D
...
hugo v0.120.3-a4892a07b41b7b3f1f143140ee4ec0a9a5cf3970+extended darwin/arm64 BuildDate=2023-11-01T17:57:00Z VendorInfo=gohugoio

ERROR [en] REF_NOT_FOUND: Ref "about-hugo" from page "posts/post-title.md": page not found
```

The issue arises because my About post in `content/` is not named `about-hugo`, it's just named `about`.

Fix option 1 (falls onto users): when migrating to `[params.author]`, one has to override both `name` and `about`:

```toml
[params.author]
name = "James Braza"
about = "about"
```

Fix option 2 (falls onto hermit-v2): removing the `[params.author]` section from the `main` branch's `hugo.toml`

What do you think? I am not sure which is the better route.

**Comment by 1bl4z3r** [comment]
Hi @jamesbraza,

Editing 'hugo.toml' is evident if user wants flexibility and customization (which is the themes' motto).

A user should create a hugo.toml for his site in root.

I had never thought of this. So, in next push, I thinking to rename 'hugo.toml' to 'hugo.toml.example', so that a user have to create a 'hugo.toml'.

Let me know if this is acceptable, as about page could be different for all users, and it would be stupid of me if I should omit this crucial section.

**Comment by jamesbraza** [comment]
Yeah I like what you suggest, it ensures:

- There's a zero-chance of bleed-over from theme config to end-users
- The theme's defaults live in-source, as opposed to relying on a `hugo.toml` config

Feel free to go down that route

---

An alternate solution could be a `hugo.toml` with more generalized defaults.  Perhaps the most generalized default is not specifying the fields within `params.author`. For example you could rely on the user to read [Explaining Configs](https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/), or have the repo's `hugo.toml` be:

```toml
[params.author]
# about = "replace-me"
# name = "Replace Me"
```

**Comment by 1bl4z3r** [comment]
What I'm thinking. I will remove hugo.toml which is used to generate the Demo site and add a new file called "hugo.toml.example".

There, I'll either comment out everything or put in default Replace Me values, and a link to Demosite's hugo.toml where user can see how that value is populated.

**Comment by 1bl4z3r** [comment]
Added hugo.toml.example in place of hugo.toml with additional help on how to setup, so unless you have a hugo.toml in root, theme will not compile

**Comment by jamesbraza** [comment]
Nice job! Looks like my site still works after this change 👌 

An aside is it may good to go with `staging` branch's `readTimeSeparator`, I feel like that default is generalized

**Comment by 1bl4z3r** [comment]
Yep, `readTimeSeparator` is meant to be changed. You may copy from staging's toml, I'm not gonna stop you 😂😂
