### ISSUE TITLE
themeColor in hugo.toml does not appear to function as expected

### ISSUE THREAD

**Issue by alexhaydock** [1bl4z3r/hermit-V2#49]
Hi!

Maybe I'm misunderstanding the purpose of the `themeColor` option in `hugo.toml`, but I can't get it to work as it should.

In the example, this is set to '#494f5c'

https://github.com/1bl4z3r/hermit-V2/blob/93f7434e64b8ffec8fc3c127eef2593f6037cda3/hugo.toml.example#L68

And this does match the background colour I get when I use this value in my `hugo.toml`. But if I change this value, I can't see what changes.

From what I can tell, most of the theme colour values are hard-coded in `_predefined.scss`:

https://github.com/1bl4z3r/hermit-V2/blob/93f7434e64b8ffec8fc3c127eef2593f6037cda3/assets/scss/_predefined.scss#L2-L7

And I can't really see where themeColor actually gets used, apart from here:

https://github.com/1bl4z3r/hermit-V2/blob/93f7434e64b8ffec8fc3c127eef2593f6037cda3/layouts/partials/site-meta.html#L14

But I'm not sure it's working correctly. Any ideas?

**Comment by 1bl4z3r** [comment]
Hi @alexhaydock,

Yes, it is confusing to the highest degree, but I am forced to keep it like that for... say with me... backward compatibility.

The use of themeColor variable is to populate "a suggested color that user agents should use to customize the display of the page or of the surrounding user interface."

MDN link for the same : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color

Is this stupid? Yes. And my brain was unable to come up with any new ideas on how to re-implement that

**Comment by 1bl4z3r** [comment]
Hi @alexhaydock
I am closing this issue as there is no update from your side.
Feel free to re-open if you like to suggest changes.

Cheerio
