### ISSUE TITLE
Few icons don't render.

### ISSUE THREAD

**Issue by dnikoloski** [1bl4z3r/hermit-V2#53]
Discord, Twitter and few other icons don't render properly for me.

How it looks on my website.
![image](https://github.com/1bl4z3r/hermit-V2/assets/119594993/5b2a6933-8109-4a63-bd6b-9f2d4c0a9309)

Code snippet from the Elements:
![image](https://github.com/1bl4z3r/hermit-V2/assets/119594993/b7731f9d-30b1-4c3d-bc8a-991eacc72c3e)

**Comment by 1bl4z3r** [comment]
Hi @dnikoloski,

That's simply not possible. All SVG icons are rendered.

Could you give further explanation on how did you setup the theme or/and your browser (if it is hardened, has some blockers enabled etc.) If possible could you please test with Vanilla Chromiun or Firefox browsers?

**Comment by dnikoloski** [comment]
Hi @1bl4z3r, thanks for reply.

You are totally right, It was my bad, I forgot to check out layouts directory, that had a few custom icons in it and overwrote the theme's ones.

Solved now.

**Comment by 1bl4z3r** [comment]
That's the LMAO moment, if I have ever seen one.

Glad it got resolved.
