### ISSUE TITLE
Remove language code from the URL

### ISSUE THREAD

**Issue by anuramat** [1bl4z3r/hermit-V2#54]
I'm not using any of the i18n features, is it possible to remove `/en/` from the urls?

**Comment by 1bl4z3r** [comment]
Hi @anuramat,

If you are using `hugo.toml.example` as the base of your site, it automatically removes i8n features, defaulted to en-US.

Additionally, you may also want to remove  following lines fron hugo.toml

```
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
```

**Comment by 1bl4z3r** [comment]
Closing this issue due to no updates/ replies. 

Re-open if required

**Comment by anuramat** [comment]
thanks for the help :bowing_man:
