### ISSUE TITLE
Add to Sites using hermit-V2

### ISSUE THREAD

**Issue by xuhdev** [1bl4z3r/hermit-V2#59]
- **Site Name** : 8 Hobbies
- **Site URL** : https://www.8hobbies.com
- [x] **Add / Edit my site**
    _Description_ : Homepage of 8 Hobbies, dedicated to web technology and open source.
-  [ ] **Remove my site**
    Please remove my site from `Sites using hermit-V2` wiki

**Comment by 1bl4z3r** [comment]
Wiki updated for your site. Thanks for using Hermit-V2

![image](https://github.com/1bl4z3r/hermit-V2/assets/34515568/1765e242-f8be-474f-a041-814c813a57d6)
