### ISSUE TITLE
Add to Sites using hermit-V2

### ISSUE THREAD

**Issue by adamhsparks** [1bl4z3r/hermit-V2#70]
- **Site Name** : Adam H. Sparks
- **Site URL** : https://adamhsparks.netlify.app/
- [x] **Add / Edit my site**
    _Description_ : Biometry, agricultural data analysis, systems and plant disease modelling, and professional cat herding

**Comment by 1bl4z3r** [comment]
Hi @adamhsparks,

Thanks for using the theme. Hope you like it

**Comment by 1bl4z3r** [comment]
Hi @adamhsparks,

Site has been added to Wiki.
Link - https://github.com/1bl4z3r/hermit-V2/wiki

Hope you like the theme
