### ISSUE TITLE
[BUG] - No word count due to missing translation table

### ISSUE THREAD

**Issue by bovender** [1bl4z3r/hermit-V2#72]
**Describe the bug**
When first using the hermit-V2 theme, no word count will be output for posts.

This is because the partial `[posts-single-info.html](https://github.com/1bl4z3r/hermit-V2/blob/5ee9c821259bda1867ba3708992a8aa97bd095ed/layouts/partials/posts_single_info.html#L12)` references a translation key `wordCount`, which by default does not exist:

```html
<p>{{- partial "svg.html" (dict "context" . "name" "posts_single_wordcount") }}{{ i18n "wordCount" . -}} {{- partial "readTime.html" . -}}</p>
```

This confused me for a little while.

One could include a file `i18n/en.toml` in the theme directory structure with a "default" English translation, and explain in the README what to do if languages other than English are used.

What do you think?

**Comment by 1bl4z3r** [comment]
Hi @bovender,

Thanks for the bug; and you're absolutely right. I'm an certified idiot. I overlooked dependence on translation key.
For the time being please use the translation key from [staging](https://github.com/1bl4z3r/hermit-V2/tree/staging/i18n).

Rest assured, I'm going to update it within a few days

**Comment by 1bl4z3r** [comment]
Hi @bovender,

I have changed few places to remove dependency on Translation key for **English Language** only. Also, I have updated [Readme](https://github.com/1bl4z3r/hermit-V2#translations) on how the translations work. Please let me know if you encounter any issues related to this, I would be happy to help.

**Comment by bovender** [comment]
Hi @1bl4z3r 

Thanks so much, tried it, works great & I even discovered that the 404 page is supposed to have some text in it :rofl:
