### ISSUE TITLE
humanmademark.com is moved to brainmade.org

### ISSUE THREAD

**Issue by vanodevium** [1bl4z3r/hermit-V2#73]
Please change links and images. 
Thanx!

**Comment by 1bl4z3r** [comment]
Hi @vanodevium,

You're absolutely right. I should've changed. The link has changed for no discernible reason.

I shall update in this weekend. Thanks for letting me know 😃

**Comment by 1bl4z3r** [comment]
Hi @vanodevium again,

Links and SVG are changed to Brainmade.
Closing this issue.

Re-open if you find any conflicts.
