### ISSUE TITLE
Improvement: split _predefined.scss

### ISSUE THREAD

**Issue by vanodevium** [1bl4z3r/hermit-V2#74]
It would be useful for customize own site.

For example: 

- _theme.scss (for theme colors)
- _fonts.scss (for fonts)
- _admonition.scss (for colors and background-colors)
- _variables.scss (for some variables, like dimmed opacity value)

> mixins must be moved from this file forever.

So if a developer wants to change something, he doesn't override the full **_predefined**, just a small part.

**Comment by 1bl4z3r** [comment]
Hi @vanodevium,

Somehow that makes perfect sense.
I am currently looking into it.

**Comment by 1bl4z3r** [comment]
Hi,

I was able to decouple colors, admonition and fonts, but didn't find a good way to remove mixins, which needs to be checked thoroughly.

For now `_predefined` remains with the mixin, and it needs testing.

**Comment by vanodevium** [comment]
@1bl4z3r 

Let me help you with this, I'll make pull request

**Comment by 1bl4z3r** [comment]
You @vanodevium, kind sir, have my utmost respect.
Closing this issue.
