### ISSUE TITLE
Question: _syntax.scss

### ISSUE THREAD

**Issue by vanodevium** [1bl4z3r/hermit-V2#77]
What for there is this file? 

How to see this styling in action?

**Comment by 1bl4z3r** [comment]
Hello again @vanodevium,

This is used for syntax highlighting.
You can see this in action in the [Typography Page](https://1bl4z3r.github.io/hermit-V2/en/posts/typography/)

![image](https://github.com/user-attachments/assets/7b55a513-225c-4377-9d17-c1ae28c5aa47)

**Comment by vanodevium** [comment]
@1bl4z3r 

So, it is just custom styling for [hugo highlight](https://gohugo.io/content-management/syntax-highlighting/) ?

If yes, issue can be closed :)

**Comment by 1bl4z3r** [comment]
Short answer, Yep
:smiley:
