### ISSUE TITLE
[Quesstion] The description in posts appears only for pages inside the `posts` folder

### ISSUE THREAD

**Issue by arampatzis** [1bl4z3r/hermit-V2#80]
Hi @1bl4z3r. Thank you for maintaining an beautiful theme.

As the title says, the description does not appear in pages that are located in a folder with a name different than `posts`.

Is this the intended behaviour? Is there a workaround?

Thank you for your time.

**Comment by 1bl4z3r** [comment]
Hi @arampatzis,

It looks like that is the intended behavior, as it was untouched from original project. Also, I didn't account for utilizing separate directory for pages.

There is always a workaround, that requires you to get your hands dirty with layout templates. 

Or,

Gimme this weekend, I will add support for customized folder structure for pages.

**Comment by 1bl4z3r** [comment]
Hi @arampatzis,

It's me again.

I have checked thoroughly, and just wanted to let you know you can absolutely do as you have asked.

Some Mandatory General Knowledge:
* Layout of `"posts"` content is located in `/themes/hermit-V2/layouts/posts`. This would be applied to all content that is in `"posts"` folder by default. This includes all the fancy (I'm using fancy over-zealously) page descriptions, author name and tags.
* By default, layout can only be added to page that matches in the [lookup order](https://gohugo.io/templates/lookup-order/)

### So, how to apply same layout to different pages that doesn't satisfy the lookup order?

You can do that in one of two ways (after adding your pages to `/content/<YOUR_FOLDER_NAME>`):

* Copy contents of `/themes/hermit-V2/layouts/posts` to `layouts/<YOUR_FOLDER_NAME>`. There are [only two files](https://github.com/1bl4z3r/hermit-V2/tree/main/layouts/posts). 
* Add this additional front matter to your pages -

```yaml
type: posts
```
**OR**
```toml
type = 'posts'
```
---
If you are getting some weird issues, let me know in this issue thread. I will look into this.
I'm keeping this Issue as open

**Comment by arampatzis** [comment]
Thank you @1bl4z3r for the fast reply. I tried the second solution you provided and it works perfectly! Thanks!
