### ISSUE TITLE
[Feature Request] Allow user to specify a page as "noindex"

### ISSUE THREAD

**Issue by xuhdev** [1bl4z3r/hermit-V2#81]
Please consider a variable that lets a user specify whether a page should not be indexed by Search Engines. This would allow pages such terms of services, privacy policies, and even some tag pages from being indexed.

This would be similar to the `robotsNoIndex` option from [PaperMod](https://github.com/adityatelange/hugo-PaperMod/wiki/Variables).

**Comment by 1bl4z3r** [comment]
Hi @xuhdev,

That's a very good suggestion. I am checking this very thing.

Will keep you posted...

**Comment by 1bl4z3r** [comment]
Hi @xuhdev,

You can now customize how you can use robots meta.

- `denyRobots` : Specify what directives to follow when denying crawlers. Default is **noindex, nofollow, noarchive**
- `allowRobots` : Specify what directives to follow when allowing crawlers. Default is **index, follow**

For specific pages:
- `noIndex` : When set to true, the page has ___noindex, nofollow, noarchive___ (unless specified by `denyRobots` added to robots meta tag. Else, robots tag will have ___index, follow___ (unless specified by `allowRobots`) 

For whole site (not sure why one would want that):
- `noIndex` : When set to true, whole site will have ___noindex, nofollow, noarchive___ (unless specified by `denyRobots`) added to robots meta tag. Else, robots tag will have ___index, follow___ (unless specified by `allowRobots`) applied to whole site


Let me know if you find any other issues, suggestions regarding this.

**Comment by 1bl4z3r** [comment]
Hi @xuhdev,

You can now customize how you can use robots meta.

- `denyRobots` : Specify what directives to follow when denying crawlers. Default is **noindex, nofollow, noarchive**
- `allowRobots` : Specify what directives to follow when allowing crawlers. Default is **index, follow**

For specific pages generated by user:
- `noIndex` : When set to true, the page has ___noindex, nofollow, noarchive___ (unless specified by `denyRobots` added to robots meta tag. Else, robots tag will have ___index, follow___ (unless specified by `allowRobots`) 

For specific pages generated by Hugo:
- `noIndexPages` : Specify on which pages crawlers will be denied. Pages specified will have ___noindex, nofollow, noarchive___ (unless specified by `denyRobots` added to robots meta tag. Use **Page title** to select pages. Useful for the pages generated by Hugo. Eg.
```
noIndexPages = ["404 Page not found", "Tags"]
```

For whole site (not sure why one would want that):
- `siteNoIndex` : When set to true, whole site will have ___noindex, nofollow, noarchive___ (unless specified by `denyRobots`) added to robots meta tag. Else, robots tag will have ___index, follow___ (unless specified by `allowRobots`) applied to whole site


Let me know if you find any other issues, suggestions regarding this.

**Comment by xuhdev** [comment]
It works, thanks!
