### ISSUE TITLE
Add to Sites using hermit-V2

### ISSUE THREAD

**Issue by Omega9** [1bl4z3r/hermit-V2#82]
- **Site Name** : Omega9
- **Site URL** : https://omega9.web.app
- [x] **Add / Edit my site**
    _Description_ : Personal page, articles about music and music software or just software, links.
-  [ ] **Remove my site**
    Please remove my site from `Sites using hermit-V2` wiki

**Comment by 1bl4z3r** [comment]
Hi @Omega9,

Your site is added to list.

Thank you for utilizing Hermit-V2 for your project. Hope you like it
