### ISSUE TITLE
Support Non Animated

### ISSUE THREAD

**Issue by paisleyrob** [1bl4z3r/hermit-V2#84]
Would you accept Pull Requests that disable animation entirely?

Rather than override the following:

* assets/scss/_animate.scss
* layouts/404.html
* layouts/_default/list.html
* layouts/_default/single.html
* layouts/partials/footer.html
* layouts/partials/header.html
* layouts/partials/social-share.html
* layouts/partials/svg.html
* layouts/posts/single.html

I'd add a configuration like `useAnimation = true` as a default so nothing changes, but I could set it to `false` and wouldn't include anything animation related.

**Comment by 1bl4z3r** [comment]
Hi @paisleyrob,

Yes, I would absolutely accept PR.
Although before submitting PR, I would urge you to throughly test if it breaks other components or not.

I.e. If animation is disabled, but a component has animation and vice-versa

**Comment by 1bl4z3r** [comment]
Closing this issue as no further information was provided.
Re-open if you have any more information to add and/or ask.

**Comment by paisleyrob** [comment]
Sorry I haven't gotten to this yet. Hopefully this week. Leave it closed for the moment as I'm not sure when I'll get to it.

**Comment by 1bl4z3r** [comment]
Hi @paisleyrob,

Don't be so hard on yourself. This ain't life or death situation. Whenever you would be free and able, you can send a PR.

Wishing you the very best
