### ISSUE TITLE
Add to Sites using hermit-V2 

### ISSUE THREAD

**Issue by v0y4g3r** [1bl4z3r/hermit-V2#87]
- **Site Name** : Ratuthomm
- **Site URL** : https://huanglei.rocks/
- [x] **Add / Edit my site**
    _Description_ : Posts about database development and some photos.
-  [ ] **Remove my site**
    Please remove my site from `Sites using hermit-V2` wiki

**Comment by 1bl4z3r** [comment]
Hi @v0y4g3r,

Site has been added to Wiki.
Link - https://github.com/1bl4z3r/hermit-V2/wiki

Hope you like the theme
