### ISSUE TITLE
Add to Sites using hermit-V2

### ISSUE THREAD

**Issue by angezanetti** [1bl4z3r/hermit-V2#91]
- **Site Name** : XVRC
- **Site URL** : https://angezanetti.com
- [x] **Add**
    _Description_ : Personal blog, of a tech entrepreneur (me). I share insights on startups, tech projects, and entrepreneurship while showcasing my current ventures. I also include various tutorials and reflections.

**Comment by 1bl4z3r** [comment]
Hi @angezanetti

Site has been added to Wiki.
Link - https://github.com/1bl4z3r/hermit-V2/wiki

Hope you like the theme
