### ISSUE TITLE
[BUG] - RSS icon still visible, even when attempting fixes on bug #58

### ISSUE THREAD

**Issue by deepankardatta** [1bl4z3r/hermit-V2#96]
**Describe the bug**
I am trying to disable the RSS icon on the bottom of a generated page. I want to get an effect similar to https://www.8hobbies.com (from the project wiki page) where there are just clean links at the bottom. I have seen @xuhdev's bug report #58 which was closed. However I cannot seem to replicate disabling the RSS icon, on either the main index page, or a sub page.

For reference my projected website is just being worked on in draft mode. It will be simple - a main page, and an about page. That's all it needs to be. 

**To Reproduce**
TOML copied from the hermit-v2 GitHub and edited
I have added the following things as bug #58 
I have added "disableKinds = ["RSS"]"
I have added the [outputs] block as described

**Terminal Output**
On the draft Hugo server mode, when do the above lines the following warnings appear:
```
WARN  Unknown kind "baseurl" in outputs configuration.
WARN  Unknown kind "theme" in outputs configuration.
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

**Expected behavior**
No RSS icon. If possible, not even the "dot" icon to separate links in the footer.

Curiously clicking on the RSS icon on the main page leads to a XML file, whereas clicking on it on my about page (created as a separate .md file through Hugo) gives me a nice 404 page.

**Desktop (please complete the following information):**
 - OS: Raspberry Pi OS 12 (Bookworm) on RPi 5
 - Browser: Firefox
 - Version: 131.0.3

**Hugo (please complete the following information):**
- Hugo: v0.136.5 - via snap package
- Extended? yes
- Latest hermit-V2 theme package? yes

**Additional context**
I have minimal experience in Hugo, so just trying it out. I like the theme. I will also write another bug report, as I think looking at the output of the Hugo server, some of the other attributes in the toml file are to be deprecated in future versions of Hugo. Thanks for looking and creating such a good theme.

**Comment by 1bl4z3r** [comment]
Hi @deepankardatta,

Sorry for not having a proper documentation for this. What you can do is edit `hugo.toml` and add below lines (There's an example in [Staging as well](https://github.com/1bl4z3r/hermit-V2/blob/f370af14100589f7e9871c5f5f3e899841abd176/hugo.toml#L5-L11) to get an idea on where to add the lines), but forgot to add that to example.

```toml
[outputs]
  home = ['html']
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']
```

Let me know if this resolves; else we will have a gander into it.

**Comment by deepankardatta** [comment]
> Hi @deepankardatta,
> 
> Sorry for not having a proper documentation for this. What you can do is edit `hugo.toml` and add below lines (There's an example in [Staging as well](https://github.com/1bl4z3r/hermit-V2/blob/f370af14100589f7e9871c5f5f3e899841abd176/hugo.toml#L5-L11) to get an idea on where to add the lines), but forgot to add that to example.
> 
> ```toml
> [outputs]
>   home = ['html']
>   page = ['html']
>   section = ['html']
>   taxonomy = ['html']
>   term = ['html']
> ```
> 
> Let me know if this resolves; else we will have a gander into it.
> 
> Also, disableKinds is high AF, it never does what we ask it to do. [#58 (comment)](https://github.com/1bl4z3r/hermit-V2/issues/58#issuecomment-2031251505)

Thanks for the help.

Having the outputs section as you described does not work.

However then deleting the output section, and keeping 'disableKinds' has made it work. I however cannot tell you **why** this works - it just does. Thanks for suggestion. I am now off to battle CSS issues in the generated site!

**Comment by 1bl4z3r** [comment]
Hi again @deepankardatta,

That doesn't make any logical sense to me whatsoever. It might be possible that there is some caching going on but I'm still as confused as you.

If possible, can you share your site (minus all confidential information) so that I can have an in-production site. You can create a private repo and add me to it or drop a mail (whichever is easier)

I will look into this this weekend and update you on my findings, till then I'm keeping this issue open.

**Comment by deepankardatta** [comment]
I've uploaded a zip file to a private GitHub repository (apologies, everything's on multiple computer, not synced up, and it seemed the easiest way to do it)

**Comment by 1bl4z3r** [comment]
Sure, I'm checking yours along with mine to find any similarities or differences in terms of RSS.

Give me this weekend

**Comment by 1bl4z3r** [comment]
Hi @deepankardatta,

I was checking yours and found that I am still confused as ever. Not sure how to make disable RSS properly. I will be checking it in the coming days.

**Comment by deepankardatta** [comment]
Thanks for looking. It seems to be working so I wouldn't stress too much. I just assume there's something changes in the Hugo backend that has made everything work a bit janky :- I had been trying some other themes, and Hugo has all sorts of deprecated options that themes still use.

**Comment by 1bl4z3r** [comment]
Hi @deepankardatta,

I got to know that if you make an empty `rss.xml` in `/layouts/posts`, rss generation could be prevented (Keyword being could). Not sure if it really works as I'm not in front of my computer.

If you got time you can try it out.

But, I want to know that if RSS icon is hidden or not? Can you please confirm it.

**Comment by deepankardatta** [comment]
Hi

Not trying your suggested fix, the RSS icon is hidden currently.

Does this information help?

**Comment by 1bl4z3r** [comment]
Sure, it works for me. Meanwhile, I'm gonna check how to disable RSS generation completely and not resort to hacking the poop out it 😆 

In the meantime, I'm closing this issue. Feel free to re-open if required.
